# Generated by Django 4.2.6 on 2024-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASVZ_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondepompstatus',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sondepompstatus',
            name='message',
            field=models.TextField(default='Geen bericht'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sondepompstatus',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
