# Generated by Django 4.2.6 on 2024-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASVZ_APP', '0002_sondepompstatus_device_id_sondepompstatus_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondepompstatus',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='sondepompstatus',
            name='message',
            field=models.TextField(default='Geen bericht'),
        ),
    ]
