# Generated by Django 4.2.6 on 2024-11-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASVZ_APP', '0003_alter_sondepompstatus_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondepompstatus',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sondepompstatus',
            name='status_type',
            field=models.CharField(choices=[('ERROR', 'Fout'), ('WARNING', 'Waarschuwing'), ('INFO', 'Informatie')], default='INFO', max_length=10),
        ),
    ]
